/**
 * Represents the application that handles users, programs, sessions, and administrative tasks.
 * Provides functionalities for login, displaying programs, revenue, participants, and managing users.
 *
 * @author Ibrahim Mashaqi
 */
package Fitness.AdminPackage;

import Fitness.InstructorP.ProgramPackage.Program;
import Fitness.InstructorP.Session.Session;

import java.util.ArrayList;
import java.util.List;

public class Application {

    /**
     * The current logged-in user.
     */
    public static User currentUser = new User();

    /**
     * List of all users in the application.
     */
    public static List<User> users;// = new ArrayList<>();

    /**
     * The current section being accessed in the application.
     */
    public static String currentSection;

    /**
     * List of all programs available in the application.
     */
    public static List<Program> programs = new ArrayList<>();

    /**
     * List of all sessions available in the application.
     */
    public static List<Session> sessions = new ArrayList<>();

    /**
     * The current feature being accessed by the user.
     */
    String currentFeature;

    /**
     * List of all programs.
     */
    public static List<Program> programsList = new ArrayList<>();

    /**
     * ID of the current program being accessed.
     */
    public static int currentProgramId;

    /**
     * List of articles not approved yet.
     */
    public static List<Article> notApprovedArticles = new ArrayList<>();

    /**
     * List of wellness-related articles.
     */
    public static List<Article> wallness = new ArrayList<>();

    /**
     * The first admin user.
     */
    public static Admin admin1;

    /**
     * The second admin user.
     */
    public static Admin admin2;

    /**
     * Logs in a user by verifying their email and password.
     *
     * @param email The email of the user.
     * @param password The password of the user.
     * @return The logged-in user if successful, otherwise null.
     */
    public static User login(String email, String password) {
       users = new ArrayList<User>();
       currentUser = new User();

        for (User user : users) {
            if (user.getEmail().equals(email) && user.getPass().equals(password)) {
                currentUser = user;
                currentUser.incPoints();
                return user;
            }
        }
        return null;
    }

    /**
     * Displays all available programs.
     */
    public static void showPrograms() {
        if (programs.isEmpty()) {
            System.out.println("No programs found");
            return;
        }
        for (Program program : programs) {
            System.out.println(program);
        }
    }

    /**
     * Displays the revenue generated by each program.
     */
    public static void showRevenue() {
        if (programs.isEmpty()) {
            System.out.println("No programs found");
            return;
        }
        for (Program program : programs) {
            System.out.println(program.getProgramTitle() + "  " + program.getRevenue());
        }
    }

    /**
     * Displays all session participants.
     */
    public static void participants() {
        if (sessions.isEmpty()) {
            System.out.println("No session found");
            return;
        }
        for (Session session : sessions) {
            System.out.println(session);
        }
    }

    /**
     * Sets the current feature being accessed.
     *
     * @param currentFeature The feature to set as current.
     */
    public void setCurrentFeature(String currentFeature) {
        this.currentFeature = currentFeature;
    }

    /**
     * Checks if a user exists with the given email.
     *
     * @param email The email to check.
     * @return True if the user exists, otherwise false.
     */
    public static boolean findUser(String email) {

        Application.login(email, "");
        for (User u : users) {
            if (u.getEmail().equals(email)) {
                return true;
            }
        }
        return false;
    }

    /**
     * Checks if a user with the given email is active.
     *
     * @param email The email to check.
     * @return True if the user is active, otherwise false.
     */
    public boolean activeCheck(String email) {
        for (User u : users) {
            if (u.getEmail().equals(email)) {
                if (u instanceof Client) {
                    Client c = (Client) u;
                    return (c.getStatus() == Status.Active);
                } else if (u instanceof Instructor) {
                    Instructor i = (Instructor) u;
                    return (i.getStatus() == Status.Active);
                }
                return true;
            }
        }
        return false;
    }

    /**
     * Checks if a user with the given email is an admin.
     *
     * @param email The email to check.
     * @return True if the user is an admin, otherwise false.
     */
    public boolean isAdmin(String email) {
        for (User u : users) {
            if (u.getEmail().equals(email)) {
                if (u instanceof Admin) {
                    return true;
                }
            }
        }
        return false;
    }

    /**
     * Initializes the application with default data.
     */
    public static void init() {
        admin1 = null;
        admin2 = null;

        admin1 = new Admin("ibrahim", 20, "male", "yaseed", "mashaqi@gmail.com", "pass");
        admin2 = new Admin("admin", 22, "male", "palestine", "admin@gmail.com", "4865");
        users.add(admin1);
        users.add(admin2);
        admin1.addClient("client", 18, "male", "yaseed", "client@gmail.com", "12345", Status.Active);
        admin1.addClient("notActive", 18, "male", "yaseed", "not@gmail.com", "12345", Status.DeActive);
        admin1.addClient("is", 18, "male", "yaseed", "is@gmail.com", "12345", Status.Active);
    }

    public static boolean addUser(User user)
    {
        if(!users.contains(user))
        {
            users.add(user);
            return true;
        }
        return false;
    }
}
